<%!
   current_ = 'about'
%>
<%inherit file="_templates/site.mako" />
<h1 class="pageTitle">About</h1>

<p><img class="inlineRight" width="128" height="128" src="http://www.gravatar.com/avatar/37d5a369729db7a9be4fb3ac9b9dd438?s=128" /> Peter Parente is a software developer in <a class="reference external" href="http://www.ibm.com/">IBM's</a> Emerging Internet Technology group. Currently he is a committer to the <a href="http://github.com/opencoweb/coweb">Open Cooperative Web Framework</a>, an IBM contribution to the <a href="http://dojofoundation.org">Dojo Foundation</a>, that grew out of IBM's <a href="http://www-01.ibm.com/software/ebusiness/jstart/bluespruce/">Project Blue Spruce</a>. His past responsibilities included developing IBM's <a href="http://live.gnome.org/LSR">Linux Screen Reader</a> and the <a href="http://live.gnome.org/Accerciser">Accerciser</a> testing tool; working on the accessibility infrastructure of the <a href="http://www.gnome.org/">GNOME desktop</a>; participating in the W3C <a href="http://www.w3.org/WAI/UA/">User Agent Accessibility Working Group</a> (UAAG); and contributing to the <a href="http://services.alphaworks.ibm.com/qedwiki/">QEDWiki</a> and <a href="http://services.alphaworks.ibm.com/mashuphub/">Mashup Hub</a> projects, the proof-of-concept software that spurred the development of the <a href="http://www-306.ibm.com/software/info/mashup-center/">IBM Mashup Center</a> product.</p>

<p>Peter holds a Ph.D. in <a href="http://www.cs.unc.edu">computer science</a> from the <a href="http://www.unc.edu/">University of North Carolina at Chapel Hill</a>. His <a href="/clique.html">dissertation</a> was about perceptually based, task oriented auditory displays for GUI applications. His goal was, and still is, to show that we can do better than reading the screen for many people with visual impairments and benefit mobile sighted users at the same time.</p>

<p>Parente's vocational and research interests include collaboration, usability, accessiblity, auditory display, and visualization. He is a <a href="http://www.python.org/">Python</a> hacker-enthusiast, but has lived in the land of JavaScript, particularly <a href="http://dojotoolkit.org">Dojo</a>, as of late. He is an avid contributor to <a href="software.html">open source projects</a>.</p>