<%inherit file="_templates/site.mako" />
<h1>Papers</h1>

<ul>
	<li>Parente, Peter and Bishop, Gary. <a href="http://doi.acm.org/10.1145/1520340.1520363">Out From Behind the Curtain: Learning from a Human Auditory Display</a>. in <em>Proceedings of the 27th international conference extended abstracts on Human factors in computing systems</em>. April, 2009.</li>
	<li>Parente, Peter. <a href="http://static.mindtrove.info/clique/parente-clique.pdf">Clique: Perceptually Based, Task Oriented Auditory Display for GUI Applications.</a> Ph.D. Thesis. University of North Carolina-Chapel Hill. July, 2008.</li>
	<li>Parente, Peter. <a  href="http://www.letsgoexpo.com/expo/index.cfm?EID=80000065&amp;p=3&amp;page=scheduledetail&amp;LCID=616&amp;ECTID=0">Linux Screen Reader: Customizing Application Access for Users and Developers</a>. in <em>Proceedings of the 2007 Annual International Technology and Persons with Disabilities Conference</em>. March, 2007.</li>
	<li>Parente, Peter and Clippingdale, Brett. <a  href="http://doi.acm.org/10.1145/1168987.1169045">Linux Screen Reader: Extensible Assistive Technology</a>. in <em>Proceedings of the Eighth international ACM conference on Assistive technologies</em>. October, 2006.</li>
	<li>Kraft, George and Parente, Peter. Accessibility Enablement and Usability for Gtk+ Applications. in <em>Proceedings of the Desktop Developers' Conference</em>. July, 2006.</li>
	<li>Parente, Peter. <a  href="http://doi.acm.org/10.1145/1127564.1127571">Clique: A conversant, task-based audio display for GUI applications</a>. Doctoral consortium participant in <em>Proceedings of the Seventh international ACM conference on Assistive technologies</em>. October, 2005.</li>
	<li>Parente, Peter. <a  href="http://doi.acm.org/10.1145/1028630.1028633">Audio Enriched Links: Web Page Previews for Blind Users</a>. in <em>Proceedings of the Sixth international ACM conference on Assistive technologies</em>. October, 2004.</li>
	<li>Jen, Dennis, Parente, Peter, Robbins, Jonathan, Weigle, Christopher, Taylor II, Russell, Burette, Alain, and Weinberg, Richard. <a  href="http://dx.doi.org/10.1109/VIS.2004.46">ImageSurfer: A Tool for Visualizing Correlations between Two Volume Scalar Fields</a>. in <em>Proceedings of the IEEE conference on Visualization</em>. October, 2004.</li>
	<li>Parente, Peter. and Bishop, Gary. <a  href="http://static.mindtrove.info/papers/BATS.pdf">BATS: The Blind Audio Tactile Mapping System</a>. in <em>Proceedings of the ACM Southeast Regional Conference</em>. March, 2003. (Outstanding Student Paper Award)</li>
	<li>Parente, Peter and Bishop, Gary. <a  href="http://static.mindtrove.info/papers/enrichments.pdf">Enrichments</a>. Unpublished paper. UNC Computer Science. 2003</li>
	<li>Jen, Dennis, Parente, Peter, Robbins, Jonathan, Weigle, Christopher, Taylor II, Russell, Burette, Alain, and Weinberg, Richard. <a  href="ftp://ftp.cs.unc.edu/pub/publications/techreports/03-033.pdf">Case Study: Investigating Dendritic Spines Using Computer Visualization Techniques</a>. Technical Report. UNC Computer Science. 2003.</li>
	<li>Parente, Peter. <a  href="http://books.google.com/books?id=w38eAPw8FBcC&amp;pg=PA61&amp;dq=webcam+image+acquisition&amp;hl=en&amp;ei=ZBURTeg8haCUB9XqlNEL&amp;sa=X&amp;oi=book_result&amp;ct=result&amp;resnum=1&amp;ved=0CCkQ6AEwAA#v=onepage&amp;q=webcam%20image%20acquisition&amp;f=false">User Solution: Webcam Image Acquisition</a>. in Image Acquisition and Processing with LabVIEW. by Relf, Christopher. CRC Press. 2003.</li>
</ul>